"""
Django settings for semilattice_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url
import ssl
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-lwp@_u6@ew&sm2%t6v!#&-m%@q*4idp=plz)1*qg5@qsc^n3s-')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'qa_app',
    'press_release_scorer',
    'headline_tester',
    'press_release_mailer',  # New: Contact management & email distribution
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'semilattice_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'semilattice_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Semilattice API Configuration
SEMILATTICE_API_KEY = config('SEMILATTICE_API_KEY')
SEMILATTICE_BASE_URL = config('SEMILATTICE_BASE', default='https://api.semilattice.ai')

# Anthropic API Configuration
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY')

# Authentication Configuration
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Email Configuration (SendGrid SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'  # Fixed username for SendGrid
EMAIL_HOST_PASSWORD = config('SENDGRID_API_KEY', default='')  # Your SendGrid API key
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='stuart@testlane.ai')

# Password Reset Configuration
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour (in seconds)

# Media Files (User Uploads - Attachments)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================
# CELERY CONFIGURATION
# ============================================

# Celery broker URL - Redis
# For local development: redis://localhost:6379/0
# For Render/Production: Use Upstash Redis with TLS (rediss://)
REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')

# Configure SSL/TLS for Upstash Redis (production)
# Upstash requires SSL connections (rediss:// protocol)
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# SSL configuration for Upstash Redis
if REDIS_URL.startswith('rediss://'):
    # Enable SSL for Upstash Redis
    CELERY_BROKER_USE_SSL = {
        'ssl_cert_reqs': ssl.CERT_NONE,  # Don't verify SSL certificates (Upstash handles this)
    }
    CELERY_REDIS_BACKEND_USE_SSL = {
        'ssl_cert_reqs': ssl.CERT_NONE,
    }

# Celery task serialization
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery task routing (disabled - using default queue for simplicity)
# CELERY_TASK_ROUTES = {
#     'press_release_mailer.tasks.send_distribution_async': {'queue': 'email'},
#     'press_release_mailer.tasks.send_single_email_async': {'queue': 'email'},
# }

# Celery task result expiration (1 hour)
CELERY_RESULT_EXPIRES = 3600



CELERY_BEAT_SCHEDULE = {
    # Check for scheduled email distributions every minute
    'check-scheduled-distributions': {
        'task': 'press_release_mailer.tasks.check_scheduled_distributions',
        'schedule': 60.0,  # Run every 60 seconds
    },
    # Example: Clean up old email logs every day at midnight UTC
    # 'cleanup-old-logs': {
    #     'task': 'press_release_mailer.tasks.cleanup_old_logs',
    #     'schedule': crontab(hour=0, minute=0),
    # },
}

# Task tracking
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
