# Generated by Django 5.2.5 on 2025-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0002_population_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='population_id',
            field=models.CharField(max_length=255),
        ),
    ]
