# Generated by Django 5.2.5 on 2025-09-24 15:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0003_alter_population_population_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='population',
            unique_together={('population_id', 'created_by')},
        ),
    ]
