# Generated by Django 5.2.5 on 2025-10-17 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_text', models.CharField(max_length=500)),
                ('angle_type', models.CharField(choices=[('hard_news', 'Hard News Angle'), ('human_interest', 'Human Interest Angle'), ('conflict_controversy', 'Conflict/Controversy Angle'), ('local_angle', 'Local Angle'), ('trend_bigger_picture', 'Trend/Bigger Picture Angle')], max_length=50)),
                ('claude_description', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(help_text='Order from Claude (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeadlineQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('max_score', models.IntegerField(default=10, help_text='Maximum score for this question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeadlineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_headline', models.CharField(max_length=500)),
                ('context_url', models.URLField(blank=True, help_text='Optional URL for context', null=True)),
                ('population_id', models.CharField(help_text='Semilattice population ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating Headlines'), ('testing', 'Testing Headlines'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('winning_headline', models.CharField(blank=True, max_length=500, null=True)),
                ('winning_score', models.IntegerField(blank=True, null=True)),
                ('original_score', models.IntegerField(blank=True, null=True)),
                ('improvement_percentage', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeadlineScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_text', models.CharField(max_length=500)),
                ('is_original', models.BooleanField(default=False)),
                ('semilattice_response_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('detailed_scores', models.JSONField(blank=True, help_text='Individual question scores', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('alternative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='headline_tester.alternativeheadline')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='headline_tester.headlinetest')),
            ],
            options={
                'ordering': ['-total_score', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='alternativeheadline',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='headline_tester.headlinetest'),
        ),
    ]
