# Generated by Django 5.2.5 on 2025-10-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headline_tester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlinescore',
            name='detailed_scores',
            field=models.JSONField(blank=True, help_text='Preference scoring details', null=True),
        ),
        migrations.AlterField(
            model_name='headlinescore',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headlinetest',
            name='original_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headlinetest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating Headlines'), ('generated', 'Headlines Generated'), ('testing', 'Testing Headlines'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='headlinetest',
            name='winning_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
