# Generated by Django 5.2.5 on 2025-09-20 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PressReleaseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_release_text', models.TextField()),
                ('total_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('source_credibility', 'Source Credibility'), ('accuracy_evidence', 'Accuracy & Evidence'), ('newsworthiness', 'Newsworthiness'), ('bias_intent', 'Bias & Intent'), ('practicality_next_steps', 'Practicality & Next Steps')], max_length=50)),
                ('category_display_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('press_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='press_release_scorer.pressreleasescore')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_number', models.IntegerField()),
                ('score', models.IntegerField()),
                ('semilattice_answer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_scores', to='press_release_scorer.categoryscore')),
            ],
        ),
    ]
