# Generated by Django 5.2.5 on 2025-09-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_release_scorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressreleasescore',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pressreleasescore',
            name='population_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pressreleasescore',
            name='processed_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pressreleasescore',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
