# Generated by Django 5.2.5 on 2025-09-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_release_scorer', '0002_pressreleasescore_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionscore',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
