# Generated by Django 5.2.5 on 2025-09-30 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_release_scorer', '0003_alter_questionscore_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressReleaseQuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Press Release Question Category',
                'verbose_name_plural': 'Press Release Question Categories',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='PressReleaseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='press_release_scorer.pressreleasequestioncategory')),
            ],
            options={
                'verbose_name': 'Press Release Question',
                'verbose_name_plural': 'Press Release Questions',
                'ordering': ['category__order', 'order', 'id'],
                'unique_together': {('category', 'order')},
            },
        ),
    ]
