# Generated by Django 5.2.5 on 2025-10-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press_release_scorer', '0004_pressreleasequestioncategory_pressreleasequestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionscore',
            options={'ordering': ['question_number']},
        ),
    ]
