# Generated by Django 5.2.5 on 2025-11-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_release_mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for background processing', max_length=255, null=True),
        ),
    ]
