# Generated by Django 5.2.5 on 2025-11-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press_release_mailer', '0002_per_user_email_uniqueness'),
        ('press_release_mailer', '0004_importjob'),
    ]

    operations = [
    ]
